// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module sha256_update (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ctx_data_address0,
        ctx_data_ce0,
        ctx_data_we0,
        ctx_data_d0,
        ctx_data_q0,
        ctx_data_address1,
        ctx_data_ce1,
        ctx_data_q1,
        m_axi_data_AWVALID,
        m_axi_data_AWREADY,
        m_axi_data_AWADDR,
        m_axi_data_AWID,
        m_axi_data_AWLEN,
        m_axi_data_AWSIZE,
        m_axi_data_AWBURST,
        m_axi_data_AWLOCK,
        m_axi_data_AWCACHE,
        m_axi_data_AWPROT,
        m_axi_data_AWQOS,
        m_axi_data_AWREGION,
        m_axi_data_AWUSER,
        m_axi_data_WVALID,
        m_axi_data_WREADY,
        m_axi_data_WDATA,
        m_axi_data_WSTRB,
        m_axi_data_WLAST,
        m_axi_data_WID,
        m_axi_data_WUSER,
        m_axi_data_ARVALID,
        m_axi_data_ARREADY,
        m_axi_data_ARADDR,
        m_axi_data_ARID,
        m_axi_data_ARLEN,
        m_axi_data_ARSIZE,
        m_axi_data_ARBURST,
        m_axi_data_ARLOCK,
        m_axi_data_ARCACHE,
        m_axi_data_ARPROT,
        m_axi_data_ARQOS,
        m_axi_data_ARREGION,
        m_axi_data_ARUSER,
        m_axi_data_RVALID,
        m_axi_data_RREADY,
        m_axi_data_RDATA,
        m_axi_data_RLAST,
        m_axi_data_RID,
        m_axi_data_RUSER,
        m_axi_data_RRESP,
        m_axi_data_BVALID,
        m_axi_data_BREADY,
        m_axi_data_BRESP,
        m_axi_data_BID,
        m_axi_data_BUSER,
        data_offset,
        len,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9
);

parameter    ap_ST_fsm_state1 = 11'd1;
parameter    ap_ST_fsm_state2 = 11'd2;
parameter    ap_ST_fsm_state3 = 11'd4;
parameter    ap_ST_fsm_state4 = 11'd8;
parameter    ap_ST_fsm_state5 = 11'd16;
parameter    ap_ST_fsm_state6 = 11'd32;
parameter    ap_ST_fsm_state7 = 11'd64;
parameter    ap_ST_fsm_state8 = 11'd128;
parameter    ap_ST_fsm_state9 = 11'd256;
parameter    ap_ST_fsm_state10 = 11'd512;
parameter    ap_ST_fsm_state11 = 11'd1024;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] ctx_data_address0;
output   ctx_data_ce0;
output   ctx_data_we0;
output  [7:0] ctx_data_d0;
input  [7:0] ctx_data_q0;
output  [5:0] ctx_data_address1;
output   ctx_data_ce1;
input  [7:0] ctx_data_q1;
output   m_axi_data_AWVALID;
input   m_axi_data_AWREADY;
output  [31:0] m_axi_data_AWADDR;
output  [0:0] m_axi_data_AWID;
output  [31:0] m_axi_data_AWLEN;
output  [2:0] m_axi_data_AWSIZE;
output  [1:0] m_axi_data_AWBURST;
output  [1:0] m_axi_data_AWLOCK;
output  [3:0] m_axi_data_AWCACHE;
output  [2:0] m_axi_data_AWPROT;
output  [3:0] m_axi_data_AWQOS;
output  [3:0] m_axi_data_AWREGION;
output  [0:0] m_axi_data_AWUSER;
output   m_axi_data_WVALID;
input   m_axi_data_WREADY;
output  [7:0] m_axi_data_WDATA;
output  [0:0] m_axi_data_WSTRB;
output   m_axi_data_WLAST;
output  [0:0] m_axi_data_WID;
output  [0:0] m_axi_data_WUSER;
output   m_axi_data_ARVALID;
input   m_axi_data_ARREADY;
output  [31:0] m_axi_data_ARADDR;
output  [0:0] m_axi_data_ARID;
output  [31:0] m_axi_data_ARLEN;
output  [2:0] m_axi_data_ARSIZE;
output  [1:0] m_axi_data_ARBURST;
output  [1:0] m_axi_data_ARLOCK;
output  [3:0] m_axi_data_ARCACHE;
output  [2:0] m_axi_data_ARPROT;
output  [3:0] m_axi_data_ARQOS;
output  [3:0] m_axi_data_ARREGION;
output  [0:0] m_axi_data_ARUSER;
input   m_axi_data_RVALID;
output   m_axi_data_RREADY;
input  [7:0] m_axi_data_RDATA;
input   m_axi_data_RLAST;
input  [0:0] m_axi_data_RID;
input  [0:0] m_axi_data_RUSER;
input  [1:0] m_axi_data_RRESP;
input   m_axi_data_BVALID;
output   m_axi_data_BREADY;
input  [1:0] m_axi_data_BRESP;
input  [0:0] m_axi_data_BID;
input  [0:0] m_axi_data_BUSER;
input  [31:0] data_offset;
input  [63:0] len;
output  [31:0] ap_return_0;
output  [63:0] ap_return_1;
output  [31:0] ap_return_2;
output  [31:0] ap_return_3;
output  [31:0] ap_return_4;
output  [31:0] ap_return_5;
output  [31:0] ap_return_6;
output  [31:0] ap_return_7;
output  [31:0] ap_return_8;
output  [31:0] ap_return_9;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[5:0] ctx_data_address0;
reg ctx_data_ce0;
reg ctx_data_we0;
reg ctx_data_ce1;
reg m_axi_data_ARVALID;
reg m_axi_data_RREADY;

(* fsm_encoding = "none" *) reg   [10:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    data_blk_n_AR;
reg    data_blk_n_R;
wire    ap_CS_fsm_state8;
wire   [0:0] icmp_ln61_fu_271_p2;
wire   [63:0] i_fu_276_p2;
reg   [63:0] i_reg_536;
reg    ap_block_state8;
reg   [7:0] data_addr_read_reg_541;
wire   [0:0] icmp_ln65_fu_353_p2;
reg   [0:0] icmp_ln65_reg_546;
wire    ap_CS_fsm_state9;
reg   [31:0] ctx_state_7_0_load_1_reg_550;
wire    ap_CS_fsm_state10;
reg   [31:0] ctx_state_6_0_load_1_reg_555;
reg   [31:0] ctx_state_5_0_load_1_reg_560;
reg   [31:0] ctx_state_4_0_load_1_reg_565;
reg   [31:0] ctx_state_3_0_load_1_reg_570;
reg   [31:0] ctx_state_2_0_load_1_reg_575;
reg   [31:0] ctx_state_1_0_load_1_reg_580;
reg   [31:0] ctx_state_0_0_load_1_reg_585;
wire    grp_sha256_transform_fu_151_ap_start;
wire    grp_sha256_transform_fu_151_ap_done;
wire    grp_sha256_transform_fu_151_ap_idle;
wire    grp_sha256_transform_fu_151_ap_ready;
wire   [5:0] grp_sha256_transform_fu_151_data_address0;
wire    grp_sha256_transform_fu_151_data_ce0;
wire   [5:0] grp_sha256_transform_fu_151_data_address1;
wire    grp_sha256_transform_fu_151_data_ce1;
wire   [31:0] grp_sha256_transform_fu_151_ap_return_0;
wire   [31:0] grp_sha256_transform_fu_151_ap_return_1;
wire   [31:0] grp_sha256_transform_fu_151_ap_return_2;
wire   [31:0] grp_sha256_transform_fu_151_ap_return_3;
wire   [31:0] grp_sha256_transform_fu_151_ap_return_4;
wire   [31:0] grp_sha256_transform_fu_151_ap_return_5;
wire   [31:0] grp_sha256_transform_fu_151_ap_return_6;
wire   [31:0] grp_sha256_transform_fu_151_ap_return_7;
reg   [63:0] i_0_reg_140;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state11;
reg    ap_block_state11_on_subcall_done;
reg    grp_sha256_transform_fu_151_ap_start_reg;
wire   [63:0] zext_ln63_fu_342_p1;
wire  signed [63:0] sext_ln63_fu_210_p1;
reg   [31:0] ctx_datalen_0_fu_64;
wire   [31:0] add_ln64_fu_347_p2;
reg   [63:0] ctx_bitlen_0_fu_68;
wire   [63:0] add_ln67_fu_396_p2;
reg   [31:0] ctx_state_7_0_fu_72;
reg   [31:0] ctx_state_6_0_fu_76;
reg   [31:0] ctx_state_5_0_fu_80;
reg   [31:0] ctx_state_4_0_fu_84;
reg   [31:0] ctx_state_3_0_fu_88;
reg   [31:0] ctx_state_2_0_fu_92;
reg   [31:0] ctx_state_1_0_fu_96;
reg   [31:0] ctx_state_0_0_fu_100;
reg   [10:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 11'd1;
#0 grp_sha256_transform_fu_151_ap_start_reg = 1'b0;
end

sha256_transform grp_sha256_transform_fu_151(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_sha256_transform_fu_151_ap_start),
    .ap_done(grp_sha256_transform_fu_151_ap_done),
    .ap_idle(grp_sha256_transform_fu_151_ap_idle),
    .ap_ready(grp_sha256_transform_fu_151_ap_ready),
    .ctx_state_0_read(ctx_state_0_0_load_1_reg_585),
    .ctx_state_1_read(ctx_state_1_0_load_1_reg_580),
    .ctx_state_2_read(ctx_state_2_0_load_1_reg_575),
    .ctx_state_3_read(ctx_state_3_0_load_1_reg_570),
    .ctx_state_4_read(ctx_state_4_0_load_1_reg_565),
    .ctx_state_5_read(ctx_state_5_0_load_1_reg_560),
    .ctx_state_6_read(ctx_state_6_0_load_1_reg_555),
    .ctx_state_7_read(ctx_state_7_0_load_1_reg_550),
    .data_address0(grp_sha256_transform_fu_151_data_address0),
    .data_ce0(grp_sha256_transform_fu_151_data_ce0),
    .data_q0(ctx_data_q0),
    .data_address1(grp_sha256_transform_fu_151_data_address1),
    .data_ce1(grp_sha256_transform_fu_151_data_ce1),
    .data_q1(ctx_data_q1),
    .ap_return_0(grp_sha256_transform_fu_151_ap_return_0),
    .ap_return_1(grp_sha256_transform_fu_151_ap_return_1),
    .ap_return_2(grp_sha256_transform_fu_151_ap_return_2),
    .ap_return_3(grp_sha256_transform_fu_151_ap_return_3),
    .ap_return_4(grp_sha256_transform_fu_151_ap_return_4),
    .ap_return_5(grp_sha256_transform_fu_151_ap_return_5),
    .ap_return_6(grp_sha256_transform_fu_151_ap_return_6),
    .ap_return_7(grp_sha256_transform_fu_151_ap_return_7)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_sha256_transform_fu_151_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            grp_sha256_transform_fu_151_ap_start_reg <= 1'b1;
        end else if ((grp_sha256_transform_fu_151_ap_ready == 1'b1)) begin
            grp_sha256_transform_fu_151_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state11_on_subcall_done) & (1'b1 == ap_CS_fsm_state11) & (icmp_ln65_reg_546 == 1'd1))) begin
        ctx_bitlen_0_fu_68 <= add_ln67_fu_396_p2;
    end else if ((~((m_axi_data_ARREADY == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        ctx_bitlen_0_fu_68 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln65_fu_353_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        ctx_datalen_0_fu_64 <= add_ln64_fu_347_p2;
    end else if (((1'b1 == ap_CS_fsm_state10) | (~((m_axi_data_ARREADY == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        ctx_datalen_0_fu_64 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state11_on_subcall_done) & (1'b1 == ap_CS_fsm_state11) & (icmp_ln65_reg_546 == 1'd1))) begin
        ctx_state_0_0_fu_100 <= grp_sha256_transform_fu_151_ap_return_0;
    end else if ((~((m_axi_data_ARREADY == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        ctx_state_0_0_fu_100 <= 32'd1779033703;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state11_on_subcall_done) & (1'b1 == ap_CS_fsm_state11) & (icmp_ln65_reg_546 == 1'd1))) begin
        ctx_state_1_0_fu_96 <= grp_sha256_transform_fu_151_ap_return_1;
    end else if ((~((m_axi_data_ARREADY == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        ctx_state_1_0_fu_96 <= 32'd3144134277;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state11_on_subcall_done) & (1'b1 == ap_CS_fsm_state11) & (icmp_ln65_reg_546 == 1'd1))) begin
        ctx_state_2_0_fu_92 <= grp_sha256_transform_fu_151_ap_return_2;
    end else if ((~((m_axi_data_ARREADY == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        ctx_state_2_0_fu_92 <= 32'd1013904242;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state11_on_subcall_done) & (1'b1 == ap_CS_fsm_state11) & (icmp_ln65_reg_546 == 1'd1))) begin
        ctx_state_3_0_fu_88 <= grp_sha256_transform_fu_151_ap_return_3;
    end else if ((~((m_axi_data_ARREADY == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        ctx_state_3_0_fu_88 <= 32'd2773480762;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state11_on_subcall_done) & (1'b1 == ap_CS_fsm_state11) & (icmp_ln65_reg_546 == 1'd1))) begin
        ctx_state_4_0_fu_84 <= grp_sha256_transform_fu_151_ap_return_4;
    end else if ((~((m_axi_data_ARREADY == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        ctx_state_4_0_fu_84 <= 32'd1359893119;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state11_on_subcall_done) & (1'b1 == ap_CS_fsm_state11) & (icmp_ln65_reg_546 == 1'd1))) begin
        ctx_state_5_0_fu_80 <= grp_sha256_transform_fu_151_ap_return_5;
    end else if ((~((m_axi_data_ARREADY == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        ctx_state_5_0_fu_80 <= 32'd2600822924;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state11_on_subcall_done) & (1'b1 == ap_CS_fsm_state11) & (icmp_ln65_reg_546 == 1'd1))) begin
        ctx_state_6_0_fu_76 <= grp_sha256_transform_fu_151_ap_return_6;
    end else if ((~((m_axi_data_ARREADY == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        ctx_state_6_0_fu_76 <= 32'd528734635;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state11_on_subcall_done) & (1'b1 == ap_CS_fsm_state11) & (icmp_ln65_reg_546 == 1'd1))) begin
        ctx_state_7_0_fu_72 <= grp_sha256_transform_fu_151_ap_return_7;
    end else if ((~((m_axi_data_ARREADY == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        ctx_state_7_0_fu_72 <= 32'd1541459225;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state11_on_subcall_done) & (1'b1 == ap_CS_fsm_state11))) begin
        i_0_reg_140 <= i_reg_536;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        i_0_reg_140 <= 64'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        ctx_state_0_0_load_1_reg_585 <= ctx_state_0_0_fu_100;
        ctx_state_1_0_load_1_reg_580 <= ctx_state_1_0_fu_96;
        ctx_state_2_0_load_1_reg_575 <= ctx_state_2_0_fu_92;
        ctx_state_3_0_load_1_reg_570 <= ctx_state_3_0_fu_88;
        ctx_state_4_0_load_1_reg_565 <= ctx_state_4_0_fu_84;
        ctx_state_5_0_load_1_reg_560 <= ctx_state_5_0_fu_80;
        ctx_state_6_0_load_1_reg_555 <= ctx_state_6_0_fu_76;
        ctx_state_7_0_load_1_reg_550 <= ctx_state_7_0_fu_72;
    end
end

always @ (posedge ap_clk) begin
    if ((~((icmp_ln61_fu_271_p2 == 1'd0) & (m_axi_data_RVALID == 1'b0)) & (icmp_ln61_fu_271_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        data_addr_read_reg_541 <= m_axi_data_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~((icmp_ln61_fu_271_p2 == 1'd0) & (m_axi_data_RVALID == 1'b0)) & (1'b1 == ap_CS_fsm_state8))) begin
        i_reg_536 <= i_fu_276_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        icmp_ln65_reg_546 <= icmp_ln65_fu_353_p2;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | (~((icmp_ln61_fu_271_p2 == 1'd0) & (m_axi_data_RVALID == 1'b0)) & (1'b1 == ap_CS_fsm_state8) & (icmp_ln61_fu_271_p2 == 1'd1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((icmp_ln61_fu_271_p2 == 1'd0) & (m_axi_data_RVALID == 1'b0)) & (1'b1 == ap_CS_fsm_state8) & (icmp_ln61_fu_271_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        ctx_data_address0 = zext_ln63_fu_342_p1;
    end else if (((1'b1 == ap_CS_fsm_state11) & (icmp_ln65_reg_546 == 1'd1))) begin
        ctx_data_address0 = grp_sha256_transform_fu_151_data_address0;
    end else begin
        ctx_data_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        ctx_data_ce0 = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state11) & (icmp_ln65_reg_546 == 1'd1))) begin
        ctx_data_ce0 = grp_sha256_transform_fu_151_data_ce0;
    end else begin
        ctx_data_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) & (icmp_ln65_reg_546 == 1'd1))) begin
        ctx_data_ce1 = grp_sha256_transform_fu_151_data_ce1;
    end else begin
        ctx_data_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        ctx_data_we0 = 1'b1;
    end else begin
        ctx_data_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        data_blk_n_AR = m_axi_data_ARREADY;
    end else begin
        data_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln61_fu_271_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        data_blk_n_R = m_axi_data_RVALID;
    end else begin
        data_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if ((~((m_axi_data_ARREADY == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        m_axi_data_ARVALID = 1'b1;
    end else begin
        m_axi_data_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if ((~((icmp_ln61_fu_271_p2 == 1'd0) & (m_axi_data_RVALID == 1'b0)) & (icmp_ln61_fu_271_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        m_axi_data_RREADY = 1'b1;
    end else begin
        m_axi_data_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((m_axi_data_ARREADY == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if ((~((icmp_ln61_fu_271_p2 == 1'd0) & (m_axi_data_RVALID == 1'b0)) & (1'b1 == ap_CS_fsm_state8) & (icmp_ln61_fu_271_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if ((~((icmp_ln61_fu_271_p2 == 1'd0) & (m_axi_data_RVALID == 1'b0)) & (icmp_ln61_fu_271_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((icmp_ln65_fu_353_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((1'b0 == ap_block_state11_on_subcall_done) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln64_fu_347_p2 = (ctx_datalen_0_fu_64 + 32'd1);

assign add_ln67_fu_396_p2 = (ctx_bitlen_0_fu_68 + 64'd512);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state11_on_subcall_done = ((grp_sha256_transform_fu_151_ap_done == 1'b0) & (icmp_ln65_reg_546 == 1'd1));
end

always @ (*) begin
    ap_block_state8 = ((icmp_ln61_fu_271_p2 == 1'd0) & (m_axi_data_RVALID == 1'b0));
end

assign ap_return_0 = ctx_datalen_0_fu_64;

assign ap_return_1 = ctx_bitlen_0_fu_68;

assign ap_return_2 = ctx_state_0_0_fu_100;

assign ap_return_3 = ctx_state_1_0_fu_96;

assign ap_return_4 = ctx_state_2_0_fu_92;

assign ap_return_5 = ctx_state_3_0_fu_88;

assign ap_return_6 = ctx_state_4_0_fu_84;

assign ap_return_7 = ctx_state_5_0_fu_80;

assign ap_return_8 = ctx_state_6_0_fu_76;

assign ap_return_9 = ctx_state_7_0_fu_72;

assign ctx_data_address1 = grp_sha256_transform_fu_151_data_address1;

assign ctx_data_d0 = data_addr_read_reg_541;

assign grp_sha256_transform_fu_151_ap_start = grp_sha256_transform_fu_151_ap_start_reg;

assign i_fu_276_p2 = (i_0_reg_140 + 64'd1);

assign icmp_ln61_fu_271_p2 = ((i_0_reg_140 == len) ? 1'b1 : 1'b0);

assign icmp_ln65_fu_353_p2 = ((add_ln64_fu_347_p2 == 32'd64) ? 1'b1 : 1'b0);

assign m_axi_data_ARADDR = sext_ln63_fu_210_p1;

assign m_axi_data_ARBURST = 2'd0;

assign m_axi_data_ARCACHE = 4'd0;

assign m_axi_data_ARID = 1'd0;

assign m_axi_data_ARLEN = len[31:0];

assign m_axi_data_ARLOCK = 2'd0;

assign m_axi_data_ARPROT = 3'd0;

assign m_axi_data_ARQOS = 4'd0;

assign m_axi_data_ARREGION = 4'd0;

assign m_axi_data_ARSIZE = 3'd0;

assign m_axi_data_ARUSER = 1'd0;

assign m_axi_data_AWADDR = 32'd0;

assign m_axi_data_AWBURST = 2'd0;

assign m_axi_data_AWCACHE = 4'd0;

assign m_axi_data_AWID = 1'd0;

assign m_axi_data_AWLEN = 32'd0;

assign m_axi_data_AWLOCK = 2'd0;

assign m_axi_data_AWPROT = 3'd0;

assign m_axi_data_AWQOS = 4'd0;

assign m_axi_data_AWREGION = 4'd0;

assign m_axi_data_AWSIZE = 3'd0;

assign m_axi_data_AWUSER = 1'd0;

assign m_axi_data_AWVALID = 1'b0;

assign m_axi_data_BREADY = 1'b0;

assign m_axi_data_WDATA = 8'd0;

assign m_axi_data_WID = 1'd0;

assign m_axi_data_WLAST = 1'b0;

assign m_axi_data_WSTRB = 1'd0;

assign m_axi_data_WUSER = 1'd0;

assign m_axi_data_WVALID = 1'b0;

assign sext_ln63_fu_210_p1 = $signed(data_offset);

assign zext_ln63_fu_342_p1 = ctx_datalen_0_fu_64;

endmodule //sha256_update
